Films/Models/Film.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Films.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.FilmActors = new HashSet<FilmActor>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int Year { get; set; }
        public string Description { get; set; }
        public string Cover { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmActor> FilmActors { get; set; }
    }
}

Films/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Films.Models;
using PagedList;

namespace Films.Controllers
{
    public class FilmsController : Controller
    {
        private FilmsEntities db = new FilmsEntities();

        // GET: Films
        public ActionResult Films(int? page)
        {
            int pageSize = 2;
            int pageNumber = (page ?? 1);
            var films = db.Films.OrderBy(c => c.Country).ToList();
            return View(films.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult MyFilms()
        {
            var films = db.Films.OrderBy(t => t.Title).ToList();
            return View(films);
        }

        public ActionResult FilmSearch(string Country)
        {
            var films = db.Films.Where(t => t.Country.Contains(Country)).OrderBy(n => n.Title).ToList();
            if (films.Count <= 0)
            {
                return HttpNotFound();
            }
            return View(films);
        }

        // GET: Films/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.Find(id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }
        public FileContentResult GetImage(int id)
        {
            Actor actor = db.Actors.FirstOrDefault(g => g.Id == id);
            if (actor != null)
            {
                return File(actor.Photo, actor.PhotoType);
            }
            return null;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Films/Views/Films/Details.cshtml
@model Films.Models.Actor

@{
    ViewBag.Title = "Details";
}

<h2>Актеры</h2>

<div class="row">
    <h4>Актер - @Html.DisplayFor(model => model.Firstname) @Html.DisplayFor(model => model.Lastname)</h4>
    <div class="col-md-3">
        @if (Model.Photo != null)
            {
            <img src="@Url.Action("GetImage", new { Model.Id})" class="image" />
        }
    </div>
    <div class="col-md-9">
        <h4>Фильмография: </h4>
        <ul>
            @foreach (var item in Model.FilmActors)
            {
                <li>@item.Film.Title</li>
            }
        </ul>
    </div>
</div>
<br />
<p>
    @Html.ActionLink("К списку фильмов", "MyFilms","Films", new { @class = "btn btn-default" })
</p>

Films/Views/Films/FilmSearch.cshtml
@model IEnumerable<Films.Models.Film>

@{
    ViewBag.Title = "FilmSearch";
}

<h2>Найденные фильмы по запросу: "@Model.First().Country"</h2>

@foreach (var item in Model)
{
    <h3>@Html.DisplayFor(modelItem => item.Title)</h3>
    <p>@Html.DisplayFor(modelItem => item.Description)</p>
    <p><b>Год выхода: </b>@Html.DisplayFor(modelItem => item.Year)</p>
    <p><b>Страна: </b>@Html.DisplayFor(modelItem => item.Country)</p>
}
<p>
    @Html.ActionLink("Назад", "Films", "Films", new { @class = "btn btn-default" })
</p>

Films/Views/Films/Films.cshtml
@model PagedList.IPagedList<Films.Models.Film>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Films";
}

<h2>Фильмы</h2>

<div class="container body-content" >
    <div style="margin-top:30px; margin-bottom:30px;">
        Найти фильм по стране:
        @using (Ajax.BeginForm("FilmSearch", "Films", new AjaxOptions { UpdateTargetId = "results" }))
        {
           <input type="text" name="Country" placeholder="Введите страну" />
           <input type="submit" value="Искать" />
        }
    </div>
</div>


@foreach (var item in Model)
{
    <h3>@Html.DisplayFor(modelItem => item.Title)</h3>
    <p>@Html.DisplayFor(modelItem => item.Description)</p>
    <p><b>Год выхода: </b>@Html.DisplayFor(modelItem => item.Year)</p>
    <p><b>Страна: </b>@Html.DisplayFor(modelItem => item.Country)</p>
    <h4>Актеры: </h4>
    <ul>
        @foreach (var task in item.FilmActors)
        {
            <li>@task.Actor.Firstname @task.Actor.Lastname</li>
        }
    </ul>
}
<br />
Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Films", new { page }))

Films/Views/Films/MyFilms.cshtml
@model IEnumerable<Films.Models.Film>

@{
    ViewBag.Title = "MyFilms";
}

<h2>Мои фильмы</h2>

@foreach (var item in Model)
{
    <div class="row">
        <h3>@Html.DisplayFor(modelItem => item.Title)</h3>
        <div class="col-md-3">
            @if (item.Cover != null)
            {
                <img src="~/Content/Images/@Html.DisplayFor(modelItem => item.Cover)" class="image" />
            }
        </div>
        <div class="col-md-8">
            <h4>Описание: </h4>
            <p>@Html.DisplayFor(modelItem => item.Description)</p>
            <p><b>Год выхода: </b>@Html.DisplayFor(modelItem => item.Year)</p>
            <p><b>Страна: </b>@Html.DisplayFor(modelItem => item.Country)</p>
            <h4>Актеры: </h4>
            <ul class="list-inline">
                @foreach (var task in item.FilmActors)
                {
                    <li>@Html.ActionLink(@task.Actor.Firstname + @task.Actor.Lastname + " ", "Details", new { id = task.Actor.Id })</li>
                }
            </ul>
        </div>
    </div>
}
    