Films/Controllers/FilmsActionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Films.Models;
using System.IO;

namespace Films.Controllers
{
    public class FilmsActionController : Controller
    {
        private FilmsEntities db = new FilmsEntities();

        // GET: FilmsAction
        [Authorize]
        public ActionResult Index()
        {
            var films = db.Films.OrderBy(t => t.Title).ToList();
            return View(films);
        }

        // GET: FilmsAction/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // GET: FilmsAction/Create
        [Authorize(Roles ="admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: FilmsAction/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Year,Description,Cover,Country")] Film film, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var filename = image.FileName;//имя файла
                    var filePathOriginal = Server.MapPath("/Content/Images");//путь куда сохраняем файл
                    string saveFileName = Path.Combine(filePathOriginal, filename);//сохранение в переменную
                    image.SaveAs(saveFileName);//сохранение
                    film.Cover = filename;
                }
                db.Films.Add(film);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(film);
        }

        // GET: FilmsAction/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // POST: FilmsAction/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Year,Description,Cover,Country")] Film film, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var filename = image.FileName;//имя файла
                    var filePathOriginal = Server.MapPath("/Content/Images");//путь куда сохраняем файл
                    string saveFileName = Path.Combine(filePathOriginal, filename);//сохранение в переменную
                    image.SaveAs(saveFileName);//сохранение
                    film.Cover = filename;
                }
                db.Entry(film).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(film);
        }

        // GET: FilmsAction/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Films.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // POST: FilmsAction/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Film film = db.Films.Find(id);
            db.Films.Remove(film);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Films/Views/FilmsAction/Create.cshtml
@model Films.Models.Film

@{
    ViewBag.Title = "Create";
}

<h2>Создание</h2>


@using (Html.BeginForm("Create", "FilmsAction", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Film</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cover, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Cover, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cover, "", new { @class = "text-danger" })
                <input type="file" name="image" class="form-control" />   
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index", "FilmsAction", new { @class="btn btn-default"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Films/Views/FilmsAction/Delete.cshtml
@model Films.Models.Film

@{
    ViewBag.Title = "Delete";
}

<h2>Удалить</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Film</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dd>
            @if (Model.Cover != null)
            {
                <img src="~/Content/Images/@Html.DisplayFor(model => model.Cover)" class="image" />
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Назад", "Index", "FilmsAction", new { @class="btn btn-default"})
        </div>
    }
</div>

Films/Views/FilmsAction/Details.cshtml
@model Films.Models.Film

@{
    ViewBag.Title = "Details";
}

<h2>Детали</h2>

<div class="row">
    <h3>@Html.DisplayFor(model => model.Title)</h3>
    <div class="col-md-3">
        @if (Model.Cover != null)
            {
            <img src="~/Content/Images/@Html.DisplayFor(model => model.Cover)" class="image" />
        }
    </div>
    <div class="col-md-8">
        <h4>Описание: </h4>
        <p>@Html.DisplayFor(model => model.Description)</p>
        <p><b>Год выхода: </b>@Html.DisplayFor(model => model.Year)</p>
        <p><b>Страна: </b>@Html.DisplayFor(model => model.Country)</p>
        <h4>Актеры: </h4>
        <ul class="list-inline">
            @foreach (var task in Model.FilmActors)
            {
                <li>@Html.ActionLink(@task.Actor.Firstname + @task.Actor.Lastname + " ", "Details", new { id = task.Actor.Id })</li>
            }
        </ul>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Назад", "Index", "FilmsAction", new { @class="btn btn-default"})
    </p>
</div>
    

Films/Views/FilmsAction/Edit.cshtml
@model Films.Models.Film

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование</h2>


@using (Html.BeginForm("Edit", "FilmsAction", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Film</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cover, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (Model.Cover != null)
                {
                    <img src="~/Content/Images/@Html.DisplayFor(model => model.Cover)" class="image" />
                }
                @Html.HiddenFor(model => model.Cover, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cover, "", new { @class = "text-danger" })
                <input type="file" name="image" class="form-control" />  
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index", "FilmsAction", new { @class="btn btn-default"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Films/Views/FilmsAction/Index.cshtml
@model IEnumerable<Films.Models.Film>

@{
    ViewBag.Title = "Index";
}

<h2>Менеджер фильмов</h2>

<p>
    @Html.ActionLink("Добавить новый", "Create")
</p>
<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-md-3">
            <h4>@Html.DisplayFor(modelItem => item.Title)</h4>

            @if (item.Cover != null)
            {
                <img src="~/Content/Images/@Html.DisplayFor(modelItem => item.Cover)" class="image" />
            }
            <br /><br />
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-default" })
            </p>
        </div>
    }
</div>